apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: hdx0315/to-do-list-app:backend-latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: todo-list
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 5000      # Service port
      targetPort: 5000  # Container port
      nodePort: 30000    # Exposed port on the node
  type: NodePort
