apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: todo-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: hdx0315/to-do-list-app:frontend-latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: todo-list
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
      nodePort: 30001  # Exposed port on the node
  type: NodePort
